# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 5%

# Ignore paths from coverage calculation
# Platform-dependent and rendering code cannot be easily unit tested
ignore:
  - "examples/**/*"
  - "internal/platform/**/*"
  - "internal/render/**/*"
  - "experimental/**/*"
  - "cmd/**/*"

# Go-specific parser settings
parsers:
  go:
    partials_as_hits: false

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
